#include "Network/RemoteStats.hpp"

#include "lib/soup/UniqueList.hpp"

#include "Core/Exceptional.hpp"
#include "Core/Spinlock.hpp"
#include "Game/pointers.hpp"

namespace Stand
{
	static Spinlock mtx;
	static soup::UniqueList<RemoteStats> instances;

	/*
	 * Keep the EXCEPTIONAL_LOCK itself in a tiny function frame.
	 *
	 * The actual operation is supplied as a reference to a callable.
	 * This prevents C++ objects owned by the caller from sharing the
	 * same stack frame as the __try generated by EXCEPTIONAL_LOCK.
	 */
	template <typename Function>
	static void exceptionalLockRemoteStats(Function& function)
	{
		EXCEPTIONAL_LOCK(mtx)
			function();
		EXCEPTIONAL_UNLOCK(mtx)
	}

	RemoteStats::RemoteStats(int64_t rid)
		: rid(rid)
	{
		results.Reset(statIds, COUNT(statIds), 1, &record, sizeof(record));

		record.m_Values[LAST_CHAR].m_Type = rage::RL_PROFILESTATS_TYPE_INVALID;

		rage::rlGamerHandle gamers[1] = { rid };
		pointers::rage_rlProfileStats_ReadStatsByGamer(0, gamers, COUNT(gamers), &results, &status);
	}

	RemoteStats* RemoteStats::get(int64_t rid)
	{
		RemoteStats* s = nullptr;

		/*
		 * This lambda owns the operation that may construct a
		 * RemoteStats. It is NOT the function containing __try,
		 * so the private constructor is accessible here.
		 */
		auto get_or_create = [&]
			{
				for (auto& inst : instances)
				{
					if (inst.rid == rid)
					{
						s = &inst;
						break;
					}
				}
				if (s == nullptr)
				{
					s = instances.emplace_back(new RemoteStats(rid));
				}
			};
		exceptionalLockRemoteStats(get_or_create);
		return s;
	}

	bool RemoteStats::tryFree(RemoteStats*& s)
	{
		if (s->isPending())
		{
			return false;
		}
		auto free_stats = [&]
			{
				instances.erase(s);
			};
		exceptionalLockRemoteStats(free_stats);

		s = nullptr;
		return true;
	}

	bool RemoteStats::shutdown()
	{
		bool done = true;

		auto shutdown_stats = [&]
			{
				for (auto i = instances.begin(); i != instances.end();)
				{
					if (i->isPending())
					{
						done = false;
						break;
					}
					i = instances.erase(i);
				}
			};
		exceptionalLockRemoteStats(shutdown_stats);

		return done;
	}
}
